# Generated by Django 5.2.4 on 2025-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_tweet_likes_alter_tweet_created_at_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='tweet_comment',
            field=models.TextField(default='No comments'),
        ),
    ]
