# Generated by Django 5.2.4 on 2025-09-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0005_alter_comment_tweet_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='images/default.jpeg', upload_to='profile_pics/'),
        ),
    ]
